[package]
name = "auto-clippy"
version = "0.1.0"
authors = ["James Graves <james.c.graves.jr@gmail.com>"]
edition = "2018"

[dependencies]
rusqlite = "0.23.1"
git2 = "0.8"
ispell = "0.3"
rustfix = { git = "https://github.com/rust-lang-nursery/rustfix", branch = "master" }
structopt = "0.2"
